### ISSUE TITLE
Workon virtuanenv

### ISSUE THREAD

**Issue by MomentByMoment** [regisf/virtualenvwrapper-powershell#17]
Workon virtuanenv is still unavailable
![workon_error](https://user-images.githubusercontent.com/55222711/75144020-212f8d80-5731-11ea-95a9-ada43ee43bb3.png)

**Comment by regisf** [comment]
Hi, 
This doesn't seems to be an error message of mine. 
When you type `workon` without environment the message is 
```
ERROR: No python venv to work on. Did you forget the -Name option?
```

since the first commit. 

Don't you use virtualenvwrapper from Guillermo López on BItBucket? 

Regards

**Comment by MomentByMoment** [comment]
hello
Yes, I have found my problem, I am sorry, I will close this problem
