### ISSUE TITLE
Load-Module is not recognized

### ISSUE THREAD

**Issue by kausality** [regisf/virtualenvwrapper-powershell#21]
Activating a virtual environment using:

``` workon venv_name ```

leads to the following error:

```
 The term 'Load-Module' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Here is the output of "host" command:

```
Name             : ConsoleHost
Version          : 5.1.19041.610
InstanceId       : f2763b19-e8bc-49db-8528-ad52b93904d5
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-IN
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

I cannot see any online doc for "Load-Module". What is this command and why is this happening?

**Comment by regisf** [comment]
Hi,
Thanks for this extremely useful bug report.  I'll will fix it on my spare time. 
R.

**Comment by regisf** [comment]
Hi @kpchand 
It seems that `Load-Module` is from the WIP branch `implement-mktempenv`. Could you please be sure you are on the `master` branch.
Regards

**Comment by kausality** [comment]
@regisf 
Can confirm that I am on master.
"Load-Module" is on line 250 in file: VirtualEnvWrapper.psm1

**Comment by regisf** [comment]
Hi @kpchand 

You were right. My apologies. 
I release a new version with the correction.

Regards
