### ISSUE TITLE
ERROR: This is the debug voice. I expected a Python version, got ****

### ISSUE THREAD

**Issue by franciscosucre** [regisf/virtualenvwrapper-powershell#3]
Hi, i am using the command

```powershell
mkvirtualenv -Python python prueba
```

But i get the following error.

```powershell
ERROR: This is the debug voice. I expected a Python version, got C:\Program Files\Python36\python.exe
```

I even receive the error when i do not use the -Python argument.

**Comment by regisf** [comment]
Thanks @franciscosucre for the bug report. This is now fixed. I added an installation script and few improvments. 
I have 6 python installed on my Windows Box and don't have problem anymore. 

Br
