### ISSUE TITLE
Suggestion: Use py instead of probing python.exe manually

### ISSUE THREAD

**Issue by madig** [regisf/virtualenvwrapper-powershell#6]
Python for Windows usually comes with the `py` wrapper executable. Launching `py` will start the highest available version of Python, `py -2` the highest available 2.x version, `py -3.6` Python 3.6.x if installed and so on. This can simplify your venv creation functions.

**Comment by regisf** [comment]
Hi, 
Thanks for you comment, but as you said : "Python comes _usually_ with `py`". 

On my work laptop, both Python 3.6 and Python 3.5 don't come with `py` executable. Both are downloaded with the default installer. 

BR
