### ISSUE TITLE
Trying to create virtenv for python2 results in an error

### ISSUE THREAD

**Issue by erezak** [regisf/virtualenvwrapper-powershell#8]
I have both python3.4 and python 2.7 installed on my machine.

When trying:
`mkvirtualenv abc -Python C:\python\27`

I get:
`ERROR: You must install virtualenv program to create the Python virtual environment 'abc'`

**Comment by erezak** [comment]
Well, if you have multiple versions of Python installed (I have 2 and 3 for 32 and 64 - total  of 4), manually install virtualenv on all of them, and it'll work.

**Comment by regisf** [comment]
Hello Erezak,

That's exactly what I wanted to say! 

The script needs `virtualenv` to be installed before all. 

Thanks for the issue.
